### PR TITLE
Use a callback to handle errors

### PR DESCRIPTION
**Pull request by sdepold**
Hey there,

I refactored the createTCPClient method. It is now able to fetch an error when it is not possible to connect the specified server. Therefore it was necessary to introduce a callback. Take a look if it appears useful to you :)

With best regards,
Sascha Depold

### CODE REVIEW

**Comment by sathorn6** [comment]
The returned socketClient should already throw an error event in this case.

**Comment by sdepold** [comment]
Yeah but I can't catch it :) Any idea?

**Comment by sidorares** [comment]
yes, socketClient has a reference to stream - client.connection

var dbclient = mysql.createTCPClient();
dbclient.connection.on('connect', foo);
dbclient.connection.on('error', bar);

**Comment by sdepold** [comment]
but I get the error when executing the following line:
  connection = net.createConnection(port, host)

**Comment by sidorares** [comment]
var mysql = require('mysql-native');
var sys = require('sys');
var dbclient = mysql.createTCPClient('bit.ly', 1234);
dbclient.auto_prepare = true;
dbclient.auth('test', 'testuser', 'testpss');
dbclient.connection.on('error', function(e) { sys.puts(e.message); } );
- I have expected line in the output "ECONNREFUSED, Connection refused"
  handler in the last line is added before any network activity and is correctly called

**Comment by sdepold** [comment]
I will test that.

**Pull request closed without merging**
