### PR TITLE
Update lib/mysql-native/commands/execute.js

### PR DESCRIPTION
**Pull request by wshager**
added UTF-8 support for both retrieving and storing strings

### CODE REVIEW

**Comment by wshager** [comment]
you might want to check for charset availability...

**Comment by sidorares** [comment]
can you add a simple test?

**Comment by wshager** [comment]
Hi Andrey,

Hope this is simple enough.

Cheers,
Wouter

2012/3/1 Andrey Sidorov <
reply@reply.github.com

> can you add a simple test?
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> 
> https://github.com/sidorares/nodejs-mysql-native/pull/60#issuecomment-4250571

## 

W.S. Hager
Lagua Web Solutions
http://lagua.nl

**Comment by sidorares** [comment]
sorry, but I don't see any tests. Did I miss something?

**Comment by wshager** [comment]
https://gist.github.com/1957443

**Comment by sja** [comment]
I think this PR is important to pull in! Please do it.

**Pull request merged**
